openapi: 3.0.1
info:
  title: Movie API
  description: An API which manages movies and ratings
  version: 0.1.0
  contact:
    name: Vlad Carcu
    email: vlad.carcu@mailinator.com
servers:
  - url: http://localhost:{port}
    description: Local server environment
    variables:
      port:
        default: '8080'
  - url: http://staging-api.example.com
    description: Staging server environment
tags:
  - name: movies
    description: All the endpoints related to the movies resource
paths:
  /movies:
    get:
      operationId: getMovies
      summary: Returns a list of movies
      description: Returns a list with all the movies, without any filters
      tags:
        - movies
      responses:
        '200':
          description: Ok response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MovieDTO'
                example:
                  - id: 1
                    name: Matrix
                    director: Wachowski Persons
                    actors:
                      - Keanu Reeves
                      - Lawrence Fishburne
        '500':
          $ref: '#/components/responses/ServerError'
    post:
      operationId: addNewMovie
      description: Adds a new movie
      tags:
        - movies
      requestBody:
        description: The movie to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovieDTO'
            example:
              name: Matrix
              director: Wachowski Persons
              actors:
                - Keanu Reeves
                - Lawrence Fishburne
      responses:
        '200':
          description: Ok response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieDTO'
        '500':
          $ref: '#/components/responses/ServerError'
  /movies/{id}/rate/{value}:
    post:
      operationId: rateMovie
      description: Rates a movie
      tags:
        - movies
      parameters:
        - name: id
          in: path
          description: Movie id
          required: true
          schema:
            type: integer
            format: int32
        - name: value
          in: path
          description: Rating (1-5)
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Ok response
        '500':
          $ref: '#/components/responses/ServerError'
components:
  responses:
    ServerError:
      description: server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDTO'
  schemas:
    ErrorDTO:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    MovieDTO:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        director:
          type: string
        actors:
          type: array
          items:
            type: string
        rating:
          type: number
          format: double